version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - npm test
      - serverless deploy --stage dev
      - serverless package --stage prod --package artifacts
artifacts:
  files:
    - artifacts/*
