version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless@1.14.0
  build:
    commands:
      - npm test
      - serverless package --package prod-artifacts
      - "sed \"s/^service: .*$/&-staging/g\" serverless.yml > serverless.yml.new"
      - rm serverless.yml
      - mv serverless.yml.new serverless.yml
      - serverless deploy
      - filename=`date +%s%3N`.zip
      - "echo $filename"
      - "zip -r $filename * -x node_modules/\\*"
      - ls -lsa
      - "aws s3 cp $filename s3://codepipeline-hello/dev/$filename"
