version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - npm test
      - serverless package --stage dev --package dev-artifacts
      - serverless package --stage prod --package prod-artifacts
artifacts:
  files:
    - dev-artifacts/*
    - prod-artifacts/*
