version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless@1.14.0
  build:
    commands:
      - serverless package --stage prod --package prod-artifacts
      - serverless package --stage dev --package dev-artifacts
      - serverless deploy --stage dev --package dev-artifacts
      - filename=`date +%s%3N`.zip
      - "echo $filename"
      - "zip -r $filename * -x node_modules/\\*"
      - "aws s3 cp $filename s3://noma-data/dev/$filename"
