version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - npm test
      - serverless package --package prod-artifacts
      - "sed \"s/^service: .*$/&-staging/g\" serverless.yml > serverless.yml.new"
      - rm serverless.yml
      - mv serverless.yml.new serverless.yml
      - serverless deploy
  post_build:
    commands:
      - rm -r node_modules
artifacts:
  files:
    - '**/*'
